flask_app/articles/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, SelectField
from wtforms.validators import DataRequired, Optional, Length
from wtf_tinymce.forms.fields import TinyMceField
from flask_wtf.recaptcha import RecaptchaField

class ArticleForm(FlaskForm):
    title = StringField("Title*", validators = [DataRequired(), Length(max  = 200)])
    content = TinyMceField("Content (autosaves every 10 seconds)", tinymce_options = {"plugins": "autosave fullscreen hr preview insertdatetime code link print searchreplace pagebreak textcolor wordcount image contextmenu table autolink", "width": "80%", "autosave_interval": "10s", "menubar": "file edit format view insert table tools",
    "toolbar": "undo redo | styleselect forecolor backcolor | fontsizeselect | bold italic underline strikethrough | alignleft, aligncenter, alignright, alignjustify | bullist, numlist, outdent, indent, blockquote | fullscreen preview", "browser_spellcheck": True, "contextmenu": "true copy cut paste | link image inserttable | cell row column deletetable",
    "content_css": "content.css", "body_class": "content_editor", "image_caption": True})
    section = SelectField("Section*", choices = [("Introduction", "Introduction"), ("Methods and Materials", "Methods and Materials"), ("Results", "Results"), ("Discussion and Conclusion", "Discussion and Conclusion"), ("Resources", "Resources"), ("References", "References"), ("Miscellaneous", "Miscellaneous")])
    submit = SubmitField("Post")

flask_app/articles/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_app import db
from flask_app.models import Article, Project
from flask_app.articles.forms import ArticleForm
from flask_app.main.forms import SearchForm
from datetime import datetime

articles = Blueprint("articles", __name__)

def collab_user(project_id):
    project = Project.query.get_or_404(project_id)
    collabs = project.collaborators
    stripped = collabs.strip()
    split_tags_list = stripped.split(", ")
    return split_tags_list

@articles.route("/project/<int:project_id>/article/<int:article_id>", methods = ["GET", "POST"])
def article(article_id, project_id):
    search_form = SearchForm()
    if search_form.submit_search.data and search_form.validate_on_submit():
        search_query = search_form.search_query.data
        return redirect(url_for("main.search", search_query = search_query, search_type = "project_search"))
    collabs = collab_user(project_id)
    project = Project.query.get_or_404(project_id)
    article = Article.query.get_or_404(article_id)
    return render_template("article.html", collabs = collabs, title = f" | {article.title}", article = article, project = project, search_form = search_form)

@articles.route("/project/<int:project_id>/article/new", methods = ["GET", "POST"])
@login_required
def new_article(project_id):
    search_form = SearchForm()
    if search_form.submit_search.data and search_form.validate_on_submit():
        search_query = search_form.search_query.data
        return redirect(url_for("main.search", search_query = search_query, search_type = "project_search"))
    form = ArticleForm()
    project = Project.query.get_or_404(project_id)
    if project.author != current_user and current_user.username not in collab_user(project_id):
        abort(403)
    if form.submit.data and form.validate_on_submit():
        article = Article(title = form.title.data, date_edited = datetime.utcnow(), content = form.content.data, section = form.section.data, overall_project = project, author = current_user)
        project.date_edited = datetime.utcnow()
        db.session.add(article)
        db.session.commit()
        flash(f"Your article has been created.")
        return redirect(url_for("articles.article", article_id = article.id, project_id = project.id))
    return render_template("create_article.html", title = " | New article", form = form, legend = "Create Article", search_form = search_form)

@articles.route("/project/<int:project_id>/article/<int:article_id>/update", methods = ["GET", "POST"])
@login_required
def update_article(article_id, project_id):
    search_form = SearchForm()
    if search_form.submit_search.data and search_form.validate_on_submit():
        search_query = search_form.search_query.data
        return redirect(url_for("main.search", search_query = search_query, search_type = "project_search"))
    project = Project.query.get_or_404(project_id)
    article = Article.query.get_or_404(article_id)
    if article.author != current_user and project.author != current_user and current_user.username not in collab_user(project_id):
        abort(403)
    form = ArticleForm()
    if form.submit.data and form.validate_on_submit():
        article.title = form.title.data
        article.content = form.content.data
        article.section = form.section.data
        project.date_edited = datetime.utcnow()
        article.date_edited = datetime.utcnow()
        article.edited_by = current_user.username
        db.session.commit()
        flash(f"Your article has been updated.")
        return redirect(url_for("articles.article", article_id = article.id, project_id = project.id))
    elif request.method == "GET":
        form.title.data = article.title
        form.content.data = article.content
        form.section.data = article.section
    return render_template("create_article.html", title = f" | Edit '{article.title}'", form = form, legend = "Update Article", search_form = search_form)

@articles.route("/project/<int:project_id>/article/<int:article_id>/delete", methods = ["POST"])
@login_required
def delete_article(article_id, project_id):
    project = Project.query.get_or_404(project_id)
    article = Article.query.get_or_404(article_id)
    project.date_edited = datetime.utcnow()
    if article.author != current_user and project.author != current_user and current_user.username not in collab_user(project_id):
        abort(403)
    db.session.delete(article)
    db.session.commit()
    flash(f"Your article has been successfully deleted.")
    return redirect(url_for("projects.project", project_id = project.id))

flask_app/projects/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from flask_app import db, bcrypt
from flask_app.models import Project, Article, Tag, User, Tube
from flask_app.projects.forms import ProjectForm, DeleteProjectForm
from flask_app.main.forms import SearchForm
from flask_app.projects.utils import save_banner
from datetime import datetime
import stripe

projects = Blueprint("projects", __name__)

@projects.route("/project/new", methods = ["GET", "POST"])
@login_required
def new_project():
    search_form = SearchForm()
    if search_form.submit_search.data and search_form.validate_on_submit():
        search_query = search_form.search_query.data
        return redirect(url_for("main.search", search_query = search_query, search_type = "project_search"))
    form = ProjectForm()
    if form.submit.data and form.validate_on_submit():
        stripped = form.tags.data.strip()
        split_tags_list = stripped.split(", ")
        if form.banner_image.data:
            project = Project(project_title = form.project_title.data.strip(), date_edited = datetime.utcnow(), banner_image = save_banner(form.banner_image.data), abstract = form.abstract.data, author = current_user, collaborators = form.collaborators.data.strip(), donations_goal = form.donations_goal.data)
            for item in split_tags_list:
                tag = Tag(tag = item, overall_project = project)
            db.session.add(tag)
            db.session.add(project)
            db.session.commit()
        else:
            project = Project(project_title = form.project_title.data.strip(), date_edited = datetime.utcnow(), abstract = form.abstract.data, author = current_user, collaborators = form.collaborators.data.strip())
            for item in split_tags_list:
                tag = Tag(tag = item, overall_project = project)
            db.session.add(tag)
            db.session.add(project)
            db.session.commit()
        flash(f"Your project has been created.")
        return redirect(url_for("projects.project", project_id = project.id))
    return render_template("create_project.html", title = " | New project", form = form, legend = "Create Project", search_form = search_form)

@projects.route("/project/<int:project_id>", methods = ["GET", "POST"])
def project(project_id):
    search_form = SearchForm()
    delete_project_form = DeleteProjectForm()
    if search_form.submit_search.data and search_form.validate_on_submit():
        search_query = search_form.search_query.data
        return redirect(url_for("main.search", search_query = search_query, search_type = "project_search"))
    project = Project.query.get_or_404(project_id)
    articles_intro = Article.query.filter_by(overall_project = project, section = "Introduction").order_by(Article.date_edited.desc()).all()
    articles_meth = Article.query.filter_by(overall_project = project, section = "Methods and Materials").order_by(Article.date_edited.desc()).all()
    articles_results = Article.query.filter_by(overall_project = project, section = "Results").order_by(Article.date_edited.desc()).all()
    articles_disc = Article.query.filter_by(overall_project = project, section = "Discussion and Conclusion").order_by(Article.date_edited.desc()).all()
    articles_resources = Article.query.filter_by(overall_project = project, section = "Resources").order_by(Article.date_edited.desc()).all()
    articles_misc = Article.query.filter_by(overall_project = project, section = "Miscellaneous").order_by(Article.date_edited.desc()).all()
    articles_ref = Article.query.filter_by(overall_project = project, section = "References").order_by(Article.date_edited.desc()).all()

    sections_list = [(articles_intro, "Introduction"), (articles_meth, "Methods and Materials"), (articles_results, "Results"), (articles_disc, "Discussion and Conclusion"), (articles_resources, "Resources"), (articles_misc, "Miscellaneous"), (articles_ref, "References")]

    tags = Tag.query.filter_by(overall_project = project)

    collabs = project.collaborators
    stripped = collabs.strip()
    split_tags_list = stripped.split(", ")
    c = []
    for item in split_tags_list:
        c.append(item)

    if current_user.is_authenticated:
        user_id = current_user.id
    else:
        user_id = None
    def toggle_colour(project_id, user_id):
        if Tube.query.filter_by(project_id = project_id, user_id = user_id).first() is not None:
            return "coloured"
        else:
            return ""
    def tube_count(project_id):
        if Tube.query.filter_by(project_id = project_id).all() is None:
            return 0
        else:
            return Tube.query.filter_by(project_id = project_id).count()

    if delete_project_form.submit_delete.data and delete_project_form.validate_on_submit():
        if project.author != current_user:
            abort(403)
        if project.author.email == delete_project_form.email.data and project.project_title == delete_project_form.project_title.data and bcrypt.check_password_hash(project.author.password, delete_project_form.password.data):
            return redirect(url_for("projects.delete_project", project_id = project.id))
        else:
            flash(f"Incorrect credentials entered.")
            return redirect(url_for("projects.project", project_id = project.id))

    if project.donations_goal:
        funding_perc = int((project.donations_amount / project.donations_goal) * 100)
        amount = int(project.donations_amount)
        goal = int(project.donations_goal)
    else:
        funding_perc = None
        amount = None
        goal = None

    project_pic = url_for("static", filename = "images/project_pics/" + project.banner_image)
    profile_pic = url_for("static", filename = "images/profile_pics/" + project.author.image_file)
    return render_template("project.html", sections_list = sections_list, amount = amount, goal = goal, funding_perc = funding_perc, title = f" | {project.project_title}", delete_project_form = delete_project_form, tube_count = tube_count, toggle_colour = toggle_colour, user_id = user_id, collabs = c, search_form = search_form, project = project, project_tags = tags, project_pic = project_pic, profile_pic = profile_pic)

@projects.route("/project/<int:project_id>/update", methods = ["GET", "POST"])
@login_required
def update_project(project_id):
    search_form = SearchForm()
    if search_form.submit_search.data and search_form.validate_on_submit():
        search_query = search_form.search_query.data
        return redirect(url_for("main.search", search_query = search_query, search_type = "project_search"))
    project = Project.query.get_or_404(project_id)
    tags = Tag.query.filter_by(overall_project = project)
    tags_len = Tag.query.filter_by(overall_project = project).count

    t = ""
    for item in tags:
        if item == tags[0]:
            t = t + item.tag
        elif tags_len != 1:
            t = t + ", " + item.tag

    if project.author != current_user:
        abort(403)
    form = ProjectForm()
    if form.submit.data and form.validate_on_submit():

        stripped = form.tags.data.strip()
        split_tags_list = stripped.split(", ")
        for tag in tags:
            db.session.delete(tag)
        for item in split_tags_list:
            tag = Tag(tag = item, overall_project = project)
        db.session.add(tag)

        project.project_title = form.project_title.data.strip()
        project.abstract = form.abstract.data
        project.donations_goal = form.donations_goal.data
        project.date_edited = datetime.utcnow()
        project.collaborators = form.collaborators.data
        if form.banner_image.data:
            picture_file = save_banner(form.banner_image.data)
            project.banner_image = picture_file
        db.session.commit()
        flash(f"Your project has been updated.")
        return redirect(url_for("projects.project", project_id = project.id))
    elif request.method == "GET":
        form.project_title.data = project.project_title
        form.abstract.data = project.abstract
        form.tags.data = t
        form.donations_goal.data = project.donations_goal
        form.collaborators.data = project.collaborators
    return render_template("create_project.html", title = f" | Edit '{project.project_title}'", form = form, legend = "Update Project", search_form = search_form)

@projects.route("/project/<int:project_id>/delete", methods = ["POST", "GET"])
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    articles = Article.query.filter_by(overall_project = project)
    tags = Tag.query.filter_by(overall_project = project)
    tubes = Tube.query.filter_by(overall_project = project)
    if project.author != current_user:
        abort(403)
    for article in articles:
        db.session.delete(article)
    for tag in tags:
        db.session.delete(tag)
    for tube in tubes:
        db.session.delete(tube)
    db.session.delete(project)
    db.session.commit()
    flash(f"Your project has been successfully deleted.")
    return redirect(url_for("main.browse"))

flask_app/templates/article.html
{% extends "layout_nav.html" %}
{% block body_content %}

<!-- Primary Page Layout
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="remodal" data-remodal-id="modal">
    <button data-remodal-action="close" class="remodal-close"></button>
    <h1><b>DELETE</b>&nbsp;&nbsp;article?</h1>
    <p>
      Are you sure you want to delete this article?
    </p>
    <br>
    <!-- <button data-remodal-action="cancel" class="remodal-cancel">Cancel</button> -->
    <form action="{{ url_for("articles.delete_article", article_id = article.id, project_id = project.id) }}", method="POST">
      <input class="remodal-confirm" type="submit" value="DELETE">
    </form>
  </div>

    <div class="article_contents">
      <div class="row inner_contents">
        <div class="eight columns article_title">
          <h3>{{ article.title }}</h3>
          <h6><a title="{{ project.project_title }}" href="{{ url_for("projects.project", project_id = project.id)}}">{{ project.project_title }}</a> ({{ article.section }})</h6>
          {% if article.author == current_user or project.author == current_user or current_user.username in collabs %}
              <a href="{{ url_for("articles.update_article", article_id = article.id, project_id = project.id) }}"><button title="Edit '{{ article.title }}'" id="edit">Edit</button></a>
              <a href="#modal"><button title="Delete '{{ article.title }}'" id="delete">Delete</button></a>
          {% endif %}
        </div>
        <div class="one column author_pic">
          <a title="{{ article.author.username }}" href="{{ url_for("users.user_projects", username = article.author.username) }}"><img src="{{ url_for("static", filename = "images/profile_pics/" + article.author.image_file) }}"></a>
        </div>
        <div class="three columns article_author">
            {% if article.author.name %}
              <p id="name">By <a style="color:black;" href="{{ url_for("users.user_projects", username = article.author.username) }}">{{ article.author.name }}</a>
                {% if project.author.verified != "False" %}
                  &nbsp;<i style="color:#AD5DD6;"class="fas fa-check-circle"></i>
                {% endif %}
              </p>
              <p id="username"><a style="color:grey;" href="{{ url_for("users.user_projects", username = article.author.username) }}">({{ article.author.username }})</a></p>
            {% else %}
              <p id="name">By <a style="color:black;" href="{{ url_for("users.user_projects", username = article.author.username) }}">{{ article.author.username }}</a>
                {% if project.author.verified != "False" %}
                  &nbsp;<i style="color:#AD5DD6;"class="fas fa-check-circle"></i>
                {% endif %}
              </p>
            {% endif %}
            <br>
            <p id="date">Created on {{ article.date_posted.strftime("%B %-d, %Y") }}</p><br>
            {% if article.edited_by %}
                <span style="color:grey">Edited by <a title="{{ article.edited_by }}" style="color:grey" href="{{ url_for("users.user_projects", username = article.edited_by) }}">{{ article.edited_by }}</a> on {{ article.date_edited.strftime("%B %-d, %Y") }}</span>
            {% endif %}
        </div>
        <div style="margin-top:40px;">
        </div>
      </div>
      <hr>
      <div class="row inner_contents">
        <div class="twelve columns article_body">
          <p>{{ article.content|safe }}</p>
        </div>
      </div>
    </div>

    <!-- <div class="article_contents">
      <div id="disqus_thread"></div>
      <script>

      /**
      *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
      *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
      /*
      var disqus_config = function () {
      this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
      this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
      };
      */
      (function() { // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');
      s.src = 'https://codon-1.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
      })();
      </script>
      <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    </div> -->

{% endblock body_content %}

flask_app/templates/create_article.html
{% extends "layout_nav.html" %}
{% block body_content %}
  {% import 'wtf_tinymce/editor.html' as tinymce with context %}

<!-- Primary Page Layout
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="row">
    <div class="form six columns offset-by-three">
      <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
          <p id="form_title">{{ legend }}<p>
          <div>
            {{ form.title.label }}
            {% if form.title.errors %}
              {{ form.title(style="border-color:#f55f5f;") }}
              <div>
                {% for error in form.title.errors %}
                  <span id="error">{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.title }}
            {% endif %}
          </div>
          <div>
            {{ form.content.label }}
            {% if form.content.errors %}
              {{ form.content(style="border-color:#f55f5f;") }}
              <div>
                {% for error in form.content.errors %}
                  <span id="error">{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.content }}
            {% endif %}
          </div>
          <div>
            {{ form.section.label }}
            {% if form.section.errors %}
              {{ form.section(style="border-color:#f55f5f;") }}
              <div>
                {% for error in form.section.errors %}
                  <span id="error">{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.section() }}
            {% endif %}
          </div>
        </fieldset>
        <div>
          {{ form.submit(title="Post your article") }}
        </div>
      </form>
    </div>
  </div>

  {{ super() }}
  {{ tinymce.init_wtf_tinymce(default_content_css='css/style.css') }}

{% endblock body_content %}

flask_app/templates/payment_options.html
<!-- Primary Page Layout
–––––––––––––––––––––––––––––––––––––––––––––––––– -->
    {% extends "layout_nonav.html" %}
    {% block body_content %}
    <div class="row">
      <div class="payment_options six columns offset-by-three">
        <div class="twelve columns"><h2>Do you want to add a payment option to enable crowdfunding features?</h2></div>
        <br><br>
        <div class="twelve columns"><h4>You can always add a payment option later in your account settings. All funding information is routed through <a target="_blank" href="https://stripe.com">Stripe</a>.</h4></div>
        <h5><b>Yes! Take me to Stripe!</b></h5>
        <a title="Link a contributor account" href="{{ url_for("payments.add_card") }}"><button style="background-color:#BF78E4;">Link a contributor account</button></a>
        <a title="Link a fundraiser account" href="https://connect.stripe.com/oauth/authorize?response_type=code&client_id=ca_DOqaAjQfCvmmdtBB5cgKlaQq9gRm8cx0&scope=read_write"><button style="background-color:#BF78E4;">Link a fundraiser account</button></a>
        <h5 style="color:#c4c1b9;">Not now, just take me to codon.</h5>
        <a title="Go to 'Browse'" href="{{ url_for("main.browse") }}"><button>Go to codon</button></a>
      </div>
    </div>

{% endblock body_content %}

flask_app/templates/project.html
{% extends "layout_nav.html" %}
{% block body_content %}

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% if current_user == project.author %}
    <div class="remodal" data-remodal-id="modal">
      <button data-remodal-action="close" class="remodal-close"></button>
      <h1><b>DELETE</b>&nbsp;&nbsp;project?</h1>
      <p>
        Are you sure you want to delete this project?
      </p>
      <br>
      <!-- <button data-remodal-action="cancel" class="remodal-cancel">Cancel</button> -->
      <form method="POST" action="" enctype="multipart/form-data">
        {{ delete_project_form.hidden_tag() }}
        <fieldset>
          <div class="update-form">
            <div>
              {{ delete_project_form.project_title.label }}
              {% if delete_project_form.project_title.errors %}
                {{ delete_project_form.project_title(style="border-color:#f55f5f;") }}
                <div>
                  {% for error in delete_project_form.project_title.errors %}
                    <span id="error">{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ delete_project_form.project_title }}
              {% endif %}
            </div>
            <div>
              {{ delete_project_form.email.label }}
              {% if delete_project_form.email.errors %}
                {{ delete_project_form.email(style="border-color:#f55f5f;") }}
                <div>
                  {% for error in delete_project_form.email.errors %}
                    <span id="error">{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ delete_project_form.email }}
              {% endif %}
            </div>
            <div>
              {{ delete_project_form.password.label }}
              {% if delete_project_form.password.errors %}
                {{ delete_project_form.password(style="border-color:#f55f5f;") }}
                <div>
                  {% for error in delete_project_form.password.errors %}
                    <span id="error">{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ delete_project_form.password(class="u-full-width") }}
              {% endif %}
            </div>
          </div>
        </fieldset>
          <div class="update-button">
            {{ delete_project_form.submit_delete }}
          </div>
      </form>
    </div>
  {% endif %}

    <div style="position: relative; height:600px; overflow:hidden; text-overflow: ellipsis;" class="twelve columns">
      <div style="background-image: url({{ project_pic }})" class="twelve columns project_banner">
      </div>
      <div class="project_header twelve columns">
        <h1><b>{{ project.project_title }}</b></h1>
      </div>
    </div>

  <div class="three columns abstract_bar">
    <a title="{{ project.author.username }}" href="{{ url_for("users.user_projects", username = project.author.username) }}"><img class="project_profile_pic" src="{{ profile_pic }}"></img></a>
    {% if project.author.name %}
      <a title="{{ project.author.username }}" href="{{ url_for("users.user_projects", username = project.author.username) }}"><h4><b>By {{ project.author.name }}</b>
        {% if project.author.verified != "False" %}
          &nbsp;<i style="color:#AD5DD6;"class="fas fa-check-circle"></i>
        {% endif %}
      </h4></a>
      <b>Username:</b> {{ project.author.username }}
    {% else %}
      <a title="{{ project.author.username }}" href="{{ url_for("users.user_projects", username = project.author.username) }}"><h4><b>By {{ project.author.username }}</b>
        {% if project.author.verified != "False" %}
          &nbsp;<i style="color:#AD5DD6;"class="fas fa-check-circle"></i>
        {% endif %}
      </h4></a>
    {% endif %}
    <br>
    {% if project.author.organization %}
      <b>Organization:</b> {{ project.author.organization }}
    {% endif %}
    {% if collabs != [""] %}
      <br><br>
      <b>Collaborators:</b>
      {% for collab in collabs %}
        <a title="{{ collab }}" href="{{ url_for("users.user_projects", username = collab) }}">{{ collab }}</a> |
      {% endfor %}
    {% endif %}
    <br>
    {% if project.author == current_user or current_user.username in collabs %}
      <a title="Create a new article for this project" href="{{ url_for("articles.new_article", project_id = project.id) }}" <i class="fas fa-file-medical new_file"></i></a>
    {% endif %}
    <br>
    <small>Created: {{ project.date_created.strftime("%B %-d, %Y") }}</small>
    <small>Last edited: {{ project.date_edited.strftime("%B %-d, %Y") }}</small>
    <br>
    {% if current_user.is_authenticated %}
      <i title="Give a tube to '{{ project.project_title }}'" user_id="{{ user_id }}" project_id="{{ project.id }}" class="fas fa-vial {{ toggle_colour(project.id, user_id) }}"></i>
    {% else %}
      <a title="You must be logged in to give tubes" href="{{ url_for("users.login") }}"><i user_id="{{ user_id }}" project_id="{{ project.id }}" class="fas fa-vial {{ toggle_colour(project.id, user_id) }}"></i></a>
    {% endif %}
    <span style="margin-left:10px;font-size:27px" class="{{ toggle_colour(project.id, user_id) }}">{{ tube_count(project.id) }}</span>
    <br>
    {% if project.donations_goal and project.author.fundraiser_id %}
      <span style="color:#46813A;font-size:20px;">{{ funding_perc }}% of funding goal reached</span>
      <div id="funding_bar">
        {% if funding_perc > 100 %}
          <div style="width:100%;border-radius:20px;" id="inner_bar"></div>
        {% else %}
          <div style="width:{{ funding_perc }}%" id="inner_bar"></div>
        {% endif %}
      </div>
      <span style="color:#46813A;font-size:30px;">${{ amount }} contributed</span>
      <br>
      <span>of ${{ goal }} goal</span>
      <br>
      <a title="Donate to '{{ project.project_title }}'" href="{{ url_for("payments.donate", project_id = project.id) }}"><button>Donate</button></a>
    {% endif %}
    <hr>
    <p style="white-space: pre-wrap;">{{ project.abstract }}</p>
    <hr>
    <span>Tags:
      {% for tag in project_tags %}
        <a title="Explore more projects in '{{ tag.tag }}'" class="tag_links" href="{{ url_for("main.search", search_query = tag.tag, search_type = "tag_search") }}">{{ tag.tag }}</a>
      {% endfor %}
    </span>
    <br>
    {% if project.author == current_user %}
        <a title="Edit '{{ project.project_title }}'" href="{{ url_for("projects.update_project", project_id = project.id) }}"><button id="edit">Edit</button></a>
        <a title="Delete '{{ project.project_title }}'" href="#modal"><button id="delete">Delete</button></a>
    {% endif %}
  </div>

<div class="seven columns article_container">
  {% for section in sections_list %}
    {% if section[0] %}
        <div class="twelve columns article_wrapper">
          <div class="row">
            <div class="project_heading six columns">
              <h3><b>{{ section[1] }}</b></h3>
            </div>
          </div>
          {% for article in section[0] %}
            <div class="five columns article_post">
              <div class="twelve columns">
                <div style="overflow: hidden; height: 100px">
                  <a title="{{ article.title }}" href="{{ url_for("articles.article", article_id = article.id, project_id = project.id) }}"><h6>{{ article.title }}</h6></a>
                </div>
                {% if article.edited_by %}
                  <a title="{{ article.edited_by }}" href="{{ url_for("users.user_projects", username = article.edited_by) }}"><span>Edited by: {{ article.edited_by }}</span></a>
                {% else %}
                  <a title="{{ article.author.username }}" href="{{ url_for("users.user_projects", username = article.author.username) }}"><span>Created by: {{ article.author.username }}</span></a>
                {% endif %}
                  <span>{{ article.date_edited.strftime("%B %-d, %Y") }}</span>
                <hr class="hr_project">
              </div>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    {% endfor %}
  </div>


{% endblock body_content %}